### ISSUE TITLE
Connect flask app to mysql db

### ISSUE THREAD

**Issue by Milind712000** [KamandPrompt/SAC-Portal#19]
Get the env variables and connect to mysql db

**Comment by Signior-X** [comment]
I am doing this, but I think more links need to be added first in app.py 
I have thought to import the file of mysqlconnection so that any statement can be easily executed using it.

**Comment by Milind712000** [comment]
what do you mean by links ?

**Comment by Signior-X** [comment]
by links, I mean the urls, 
which we write in @app.route(link)

**Comment by Signior-X** [comment]
I have connected mysql db to app.py and also made a way to check wheather email and password are correct or not, After the Naveen's PR is accepted, I will complete it.

**Comment by Milind712000** [comment]
for this issue just include the connection to db (get credentials from .env and create a connection using sqlalchemy or flask_mysqldb or similar module)
for login and registration use a different pr 
and this needs to be done first as the other endpoints will have to fetch data from the db

**Comment by Signior-X** [comment]
#23 I hope this will solve this issue. But I think I have used the previous library mysql-connector

**Comment by Signior-X** [comment]
If you say, we can move this to sqlalchemy, but the only problem will be it will have all new commands.
So, I haven't used it. Instead preferred the basic module.
